In [1]:
from utils import load_flights

flights = load_flights(["2007", "2008"])

In [2]:
flights.memory_usage()

Index                     128
Year                 78739456
Month                78739456
DayofMonth           78739456
DayOfWeek            78739456
DepTime              78739456
CRSDepTime           78739456
ArrTime              78739456
CRSArrTime           78739456
UniqueCarrier        78739456
FlightNum            78739456
TailNum              78739456
ActualElapsedTime    78739456
CRSElapsedTime       78739456
AirTime              78739456
ArrDelay             78739456
DepDelay             78739456
Origin               78739456
Dest                 78739456
Distance             78739456
TaxiIn               78739456
TaxiOut              78739456
Cancelled            78739456
CancellationCode     78739456
Diverted             78739456
CarrierDelay         78739456
WeatherDelay         78739456
NASDelay             78739456
SecurityDelay        78739456
LateAircraftDelay    78739456
dtype: int64

In [3]:
flights.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9842432 entries, 0 to 9842431
Data columns (total 29 columns):
 #   Column             Dtype
---  ------             -----
 0   Year               int64
 1   Month              int64
 2   DayofMonth         int64
 3   DayOfWeek          int64
 4   DepTime            float64
 5   CRSDepTime         int64
 6   ArrTime            float64
 7   CRSArrTime         int64
 8   UniqueCarrier      object
 9   FlightNum          int64
 10  TailNum            object
 11  ActualElapsedTime  float64
 12  CRSElapsedTime     float64
 13  AirTime            float64
 14  ArrDelay           float64
 15  DepDelay           float64
 16  Origin             object
 17  Dest               object
 18  Distance           int64
 19  TaxiIn             float64
 20  TaxiOut            float64
 21  Cancelled          int64
 22  CancellationCode   object
 23  Diverted           int64
 24  CarrierDelay       float64
 25  WeatherDelay       float64
 26  NASDelay           float64
 27  SecurityDelay      float64
 28  LateAircraftDelay  float64
dtypes: float64(14), int64(10), object(5)
memory usage: 2.1+ GB

In [4]:
flights.describe()

,Year,Month,DayofMonth,DayOfWeek,DepTime,CRSDepTime,ArrTime,CRSArrTime,FlightNum,ActualElapsedTime,...,Distance,TaxiIn,TaxiOut,Cancelled,Diverted,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay
count,9.842432e+06,9.842432e+06,9.842432e+06,9.842432e+06,9.617242e+06,9.842432e+06,9.594409e+06,9.842432e+06,9.842432e+06,9.594409e+06,...,9.842432e+06,9.772336e+06,9.777990e+06,9.842432e+06,9.842432e+06,8.037798e+06,8.037798e+06,8.037798e+06,8.037798e+06,8.037798e+06
mean,2.007243e+03,5.541495e+00,1.571083e+01,3.927935e+00,1.339414e+03,1.330450e+03,1.483007e+03,1.495720e+03,2.194359e+03,1.268774e+02,...,7.213480e+02,6.727078e+00,1.639185e+01,2.287951e-02,2.319853e-03,4.729821e+00,9.277785e-01,4.683709e+00,2.786099e-02,6.253898e+00
std,4.287432e-01,3.484916e+00,8.773739e+00,1.989427e+00,4.799542e+02,4.649693e+02,5.074456e+02,4.823043e+02,1.967016e+03,7.096392e+01,...,5.610710e+02,5.081036e+00,1.164879e+01,1.495194e-01,4.810896e-02,2.299816e+01,1.062264e+01,1.791058e+01,1.145715e+00,2.335097e+01
min,2.007000e+03,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,0.000000e+00,1.000000e+00,0.000000e+00,1.000000e+00,1.200000e+01,...,1.100000e+01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
25%,2.007000e+03,3.000000e+00,8.000000e+00,2.000000e+00,9.300000e+02,9.290000e+02,1.108000e+03,1.115000e+03,5.930000e+02,7.600000e+01,...,3.210000e+02,4.000000e+00,1.000000e+01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
50%,2.007000e+03,5.000000e+00,1.600000e+01,4.000000e+00,1.329000e+03,1.322000e+03,1.514000e+03,1.520000e+03,1.518000e+03,1.090000e+02,...,5.740000e+02,6.000000e+00,1.400000e+01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
75%,2.007000e+03,8.000000e+00,2.300000e+01,6.000000e+00,1.733000e+03,1.720000e+03,1.911000e+03,1.908000e+03,3.577000e+03,1.570000e+02,...,9.480000e+02,8.000000e+00,1.900000e+01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
max,2.008000e+03,1.200000e+01,3.100000e+01,7.000000e+00,2.400000e+03,2.359000e+03,2.400000e+03,2.400000e+03,9.741000e+03,1.270000e+03,...,4.962000e+03,5.450000e+02,5.300000e+02,1.000000e+00,1.000000e+00,2.580000e+03,1.429000e+03,1.386000e+03,3.920000e+02,1.254000e+03